stages:
- build

fedora-28:
  stage: build
  image: fedora:28
  script:
    - dnf install -y git python rpm-build which dnf-plugins-core
    - ci/gitlab-build.sh
    - mkdir ${CI_JOB_NAME}
    - cp -r /root/rpmbuild/RPMS build/SRPMS ${CI_JOB_NAME}
  artifacts:
    paths:
    - "$CI_JOB_NAME"

fedora-29:
  stage: build
  image: fedora:28
  script:
    - dnf install -y git python rpm-build which dnf-plugins-core
    - ci/gitlab-build.sh
    - mkdir ${CI_JOB_NAME}
    - cp -r /root/rpmbuild/RPMS build/SRPMS ${CI_JOB_NAME}
  artifacts:
    paths:
    - "$CI_JOB_NAME"
