stages:
- build

fedora-27:
  stage: build
  image: fedora:27
  script:
    - yum install -y git python rpm-build which dnf-plugins-core
    - ci/gitlab-build.sh
    - mkdir ${CI_JOB_NAME}
    - cp -r /root/rpmbuild/RPMS build/SRPMS ${CI_JOB_NAME}
  artifacts:
    paths:
    - "$CI_JOB_NAME"

fedora-28:
  stage: build
  image: fedora:27
  script:
    - yum install -y git python rpm-build which dnf-plugins-core
    - ci/gitlab-build.sh
    - mkdir ${CI_JOB_NAME}
    - cp -r /root/rpmbuild/RPMS build/SRPMS ${CI_JOB_NAME}
  artifacts:
    paths:
    - "$CI_JOB_NAME"
