stages:
- build

fedora-31:
  stage: build
  image: fedora:31
  script:
    - dnf install -y git python rpm-build which dnf-plugins-core libuuid-devel
    - ci/gitlab-build.sh
    - mkdir ${CI_JOB_NAME}
    - cp -r /root/rpmbuild/RPMS build/SRPMS ${CI_JOB_NAME}
  artifacts:
    paths:
    - "$CI_JOB_NAME"

